application: shope-architect
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^fabfile\.py

handlers:
- url: /html
  static_dir: html
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest