application: window-pods
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /mail
  script: main.app
- url: /static
  static_dir: static
- url: /css
  static_dir: static/css
- url: /html
  static_dir: static/html
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: .*
  static_files: static/index.html
  upload: static/index.html

libraries:
- name: webapp2
  version: latest
