application: shope-architect
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^fabfile\.py

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /img
  static_dir: static/img
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest